#!/usr/bin/env php
<?php
/**
 * User: yk
 * Date: 19-1-10
 * Time: 2:38 pm
 */

defined('YB_DEBUG') or define('YB_DEBUG', true);

include ( __DIR__ . '/vendor/autoload.php');

try{
    include ( __DIR__ . '/server/entry.php' );

    $capsule = new Illuminate\Database\Capsule\Manager();
    include ( __DIR__ . '/config/dbConfig.php' );
    $capsule->bootEloquent();

    $app = new \Inhere\Console\Application([
        'name' => 'YB Console App',
        'version' => '1.0.0',
    ]);

    //register closure
    include ( __DIR__ . '/console/closureFiles/allClosure.php' );

    //register command
    include ( __DIR__ . '/config/command.php' );

    //register controller
    include ( __DIR__ . '/config/groups.php' );

    $app->run();
}catch (\Exception $e) {
    //out error message
    if(YB_DEBUG === true) {
        echo outError($e);
    }
}



